# Generated by Django 3.0.3 on 2020-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickynotes', '0002_auto_20200402_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='background_color',
            field=models.CharField(choices=[('white', 'white'), ('blue', 'blue'), ('yellow', 'yellow'), ('purple', 'purple'), ('red', 'red'), ('green', 'green')], default='white', max_length=25),
        ),
    ]
