# Generated by Django 3.0.3 on 2020-04-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickynotes', '0005_auto_20200402_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
